require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EfGeneralsController do

  # This should return the minimal set of attributes required to create a valid
  # EfGeneral. As you add validations to EfGeneral, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EfGeneralsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ef_generals as @ef_generals" do
      ef_general = EfGeneral.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ef_generals).should eq([ef_general])
    end
  end

  describe "GET show" do
    it "assigns the requested ef_general as @ef_general" do
      ef_general = EfGeneral.create! valid_attributes
      get :show, {:id => ef_general.to_param}, valid_session
      assigns(:ef_general).should eq(ef_general)
    end
  end

  describe "GET new" do
    it "assigns a new ef_general as @ef_general" do
      get :new, {}, valid_session
      assigns(:ef_general).should be_a_new(EfGeneral)
    end
  end

  describe "GET edit" do
    it "assigns the requested ef_general as @ef_general" do
      ef_general = EfGeneral.create! valid_attributes
      get :edit, {:id => ef_general.to_param}, valid_session
      assigns(:ef_general).should eq(ef_general)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EfGeneral" do
        expect {
          post :create, {:ef_general => valid_attributes}, valid_session
        }.to change(EfGeneral, :count).by(1)
      end

      it "assigns a newly created ef_general as @ef_general" do
        post :create, {:ef_general => valid_attributes}, valid_session
        assigns(:ef_general).should be_a(EfGeneral)
        assigns(:ef_general).should be_persisted
      end

      it "redirects to the created ef_general" do
        post :create, {:ef_general => valid_attributes}, valid_session
        response.should redirect_to(EfGeneral.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ef_general as @ef_general" do
        # Trigger the behavior that occurs when invalid params are submitted
        EfGeneral.any_instance.stub(:save).and_return(false)
        post :create, {:ef_general => {}}, valid_session
        assigns(:ef_general).should be_a_new(EfGeneral)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EfGeneral.any_instance.stub(:save).and_return(false)
        post :create, {:ef_general => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ef_general" do
        ef_general = EfGeneral.create! valid_attributes
        # Assuming there are no other ef_generals in the database, this
        # specifies that the EfGeneral created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EfGeneral.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => ef_general.to_param, :ef_general => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested ef_general as @ef_general" do
        ef_general = EfGeneral.create! valid_attributes
        put :update, {:id => ef_general.to_param, :ef_general => valid_attributes}, valid_session
        assigns(:ef_general).should eq(ef_general)
      end

      it "redirects to the ef_general" do
        ef_general = EfGeneral.create! valid_attributes
        put :update, {:id => ef_general.to_param, :ef_general => valid_attributes}, valid_session
        response.should redirect_to(ef_general)
      end
    end

    describe "with invalid params" do
      it "assigns the ef_general as @ef_general" do
        ef_general = EfGeneral.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EfGeneral.any_instance.stub(:save).and_return(false)
        put :update, {:id => ef_general.to_param, :ef_general => {}}, valid_session
        assigns(:ef_general).should eq(ef_general)
      end

      it "re-renders the 'edit' template" do
        ef_general = EfGeneral.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EfGeneral.any_instance.stub(:save).and_return(false)
        put :update, {:id => ef_general.to_param, :ef_general => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ef_general" do
      ef_general = EfGeneral.create! valid_attributes
      expect {
        delete :destroy, {:id => ef_general.to_param}, valid_session
      }.to change(EfGeneral, :count).by(-1)
    end

    it "redirects to the ef_generals list" do
      ef_general = EfGeneral.create! valid_attributes
      delete :destroy, {:id => ef_general.to_param}, valid_session
      response.should redirect_to(ef_generals_url)
    end
  end

end
