require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EfParesController do

  # This should return the minimal set of attributes required to create a valid
  # EfPare. As you add validations to EfPare, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EfParesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ef_pares as @ef_pares" do
      ef_pare = EfPare.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ef_pares).should eq([ef_pare])
    end
  end

  describe "GET show" do
    it "assigns the requested ef_pare as @ef_pare" do
      ef_pare = EfPare.create! valid_attributes
      get :show, {:id => ef_pare.to_param}, valid_session
      assigns(:ef_pare).should eq(ef_pare)
    end
  end

  describe "GET new" do
    it "assigns a new ef_pare as @ef_pare" do
      get :new, {}, valid_session
      assigns(:ef_pare).should be_a_new(EfPare)
    end
  end

  describe "GET edit" do
    it "assigns the requested ef_pare as @ef_pare" do
      ef_pare = EfPare.create! valid_attributes
      get :edit, {:id => ef_pare.to_param}, valid_session
      assigns(:ef_pare).should eq(ef_pare)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EfPare" do
        expect {
          post :create, {:ef_pare => valid_attributes}, valid_session
        }.to change(EfPare, :count).by(1)
      end

      it "assigns a newly created ef_pare as @ef_pare" do
        post :create, {:ef_pare => valid_attributes}, valid_session
        assigns(:ef_pare).should be_a(EfPare)
        assigns(:ef_pare).should be_persisted
      end

      it "redirects to the created ef_pare" do
        post :create, {:ef_pare => valid_attributes}, valid_session
        response.should redirect_to(EfPare.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ef_pare as @ef_pare" do
        # Trigger the behavior that occurs when invalid params are submitted
        EfPare.any_instance.stub(:save).and_return(false)
        post :create, {:ef_pare => {}}, valid_session
        assigns(:ef_pare).should be_a_new(EfPare)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EfPare.any_instance.stub(:save).and_return(false)
        post :create, {:ef_pare => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ef_pare" do
        ef_pare = EfPare.create! valid_attributes
        # Assuming there are no other ef_pares in the database, this
        # specifies that the EfPare created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EfPare.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => ef_pare.to_param, :ef_pare => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested ef_pare as @ef_pare" do
        ef_pare = EfPare.create! valid_attributes
        put :update, {:id => ef_pare.to_param, :ef_pare => valid_attributes}, valid_session
        assigns(:ef_pare).should eq(ef_pare)
      end

      it "redirects to the ef_pare" do
        ef_pare = EfPare.create! valid_attributes
        put :update, {:id => ef_pare.to_param, :ef_pare => valid_attributes}, valid_session
        response.should redirect_to(ef_pare)
      end
    end

    describe "with invalid params" do
      it "assigns the ef_pare as @ef_pare" do
        ef_pare = EfPare.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EfPare.any_instance.stub(:save).and_return(false)
        put :update, {:id => ef_pare.to_param, :ef_pare => {}}, valid_session
        assigns(:ef_pare).should eq(ef_pare)
      end

      it "re-renders the 'edit' template" do
        ef_pare = EfPare.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EfPare.any_instance.stub(:save).and_return(false)
        put :update, {:id => ef_pare.to_param, :ef_pare => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ef_pare" do
      ef_pare = EfPare.create! valid_attributes
      expect {
        delete :destroy, {:id => ef_pare.to_param}, valid_session
      }.to change(EfPare, :count).by(-1)
    end

    it "redirects to the ef_pares list" do
      ef_pare = EfPare.create! valid_attributes
      delete :destroy, {:id => ef_pare.to_param}, valid_session
      response.should redirect_to(ef_pares_url)
    end
  end

end
