require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EnfermedadActualsController do

  # This should return the minimal set of attributes required to create a valid
  # EnfermedadActual. As you add validations to EnfermedadActual, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EnfermedadActualsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all enfermedad_actuals as @enfermedad_actuals" do
      enfermedad_actual = EnfermedadActual.create! valid_attributes
      get :index, {}, valid_session
      assigns(:enfermedad_actuals).should eq([enfermedad_actual])
    end
  end

  describe "GET show" do
    it "assigns the requested enfermedad_actual as @enfermedad_actual" do
      enfermedad_actual = EnfermedadActual.create! valid_attributes
      get :show, {:id => enfermedad_actual.to_param}, valid_session
      assigns(:enfermedad_actual).should eq(enfermedad_actual)
    end
  end

  describe "GET new" do
    it "assigns a new enfermedad_actual as @enfermedad_actual" do
      get :new, {}, valid_session
      assigns(:enfermedad_actual).should be_a_new(EnfermedadActual)
    end
  end

  describe "GET edit" do
    it "assigns the requested enfermedad_actual as @enfermedad_actual" do
      enfermedad_actual = EnfermedadActual.create! valid_attributes
      get :edit, {:id => enfermedad_actual.to_param}, valid_session
      assigns(:enfermedad_actual).should eq(enfermedad_actual)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EnfermedadActual" do
        expect {
          post :create, {:enfermedad_actual => valid_attributes}, valid_session
        }.to change(EnfermedadActual, :count).by(1)
      end

      it "assigns a newly created enfermedad_actual as @enfermedad_actual" do
        post :create, {:enfermedad_actual => valid_attributes}, valid_session
        assigns(:enfermedad_actual).should be_a(EnfermedadActual)
        assigns(:enfermedad_actual).should be_persisted
      end

      it "redirects to the created enfermedad_actual" do
        post :create, {:enfermedad_actual => valid_attributes}, valid_session
        response.should redirect_to(EnfermedadActual.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved enfermedad_actual as @enfermedad_actual" do
        # Trigger the behavior that occurs when invalid params are submitted
        EnfermedadActual.any_instance.stub(:save).and_return(false)
        post :create, {:enfermedad_actual => {}}, valid_session
        assigns(:enfermedad_actual).should be_a_new(EnfermedadActual)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EnfermedadActual.any_instance.stub(:save).and_return(false)
        post :create, {:enfermedad_actual => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested enfermedad_actual" do
        enfermedad_actual = EnfermedadActual.create! valid_attributes
        # Assuming there are no other enfermedad_actuals in the database, this
        # specifies that the EnfermedadActual created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EnfermedadActual.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => enfermedad_actual.to_param, :enfermedad_actual => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested enfermedad_actual as @enfermedad_actual" do
        enfermedad_actual = EnfermedadActual.create! valid_attributes
        put :update, {:id => enfermedad_actual.to_param, :enfermedad_actual => valid_attributes}, valid_session
        assigns(:enfermedad_actual).should eq(enfermedad_actual)
      end

      it "redirects to the enfermedad_actual" do
        enfermedad_actual = EnfermedadActual.create! valid_attributes
        put :update, {:id => enfermedad_actual.to_param, :enfermedad_actual => valid_attributes}, valid_session
        response.should redirect_to(enfermedad_actual)
      end
    end

    describe "with invalid params" do
      it "assigns the enfermedad_actual as @enfermedad_actual" do
        enfermedad_actual = EnfermedadActual.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EnfermedadActual.any_instance.stub(:save).and_return(false)
        put :update, {:id => enfermedad_actual.to_param, :enfermedad_actual => {}}, valid_session
        assigns(:enfermedad_actual).should eq(enfermedad_actual)
      end

      it "re-renders the 'edit' template" do
        enfermedad_actual = EnfermedadActual.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EnfermedadActual.any_instance.stub(:save).and_return(false)
        put :update, {:id => enfermedad_actual.to_param, :enfermedad_actual => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested enfermedad_actual" do
      enfermedad_actual = EnfermedadActual.create! valid_attributes
      expect {
        delete :destroy, {:id => enfermedad_actual.to_param}, valid_session
      }.to change(EnfermedadActual, :count).by(-1)
    end

    it "redirects to the enfermedad_actuals list" do
      enfermedad_actual = EnfermedadActual.create! valid_attributes
      delete :destroy, {:id => enfermedad_actual.to_param}, valid_session
      response.should redirect_to(enfermedad_actuals_url)
    end
  end

end
